apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  namespace: dev
  labels:
    name: dev
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: content-api 
  template:
    metadata:
      labels:
        name: content-api
    spec: 
      containers:
      - name: content-api
        image: registry.gitlab.com/scg-it-dist/content-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: development
      imagePullSecrets:
      - name: registry.gitlab.com
