apiVersion: v1
kind: Service
metadata:
  labels:
    name: react-ssr
  name: react-ssr
  namespace: prod
spec:
  selector:
    name: react-ssr
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
