apiVersion: v1
kind: Service
metadata:
  labels:
    name: express-api
  name: express-api
  namespace: dev
spec:
  selector:
    name: express-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
