---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: nginx-lets-encrypt
spec:
  secretName: nginx-lets-encrypt-tls
  issuerRef: 
    name: letsencrypt
  commonName: www.praekiko.tk
  dnsNames:
  - praekiko.tk
  - www.praekiko.tk
  acme:
    config:
      - http01:
          ingress: default-ingress
        domains:
          - praekiko.tk
          - www.praekiko.tk