apiVersion: v1
kind: Service
metadata:
  labels:
    name: react-ssr-dev
  name: react-ssr-dev
  namespace: development
  resourceVersion: "7257"
  selfLink: /api/v1/namespaces/development/services/react-ssr-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31511
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: react-ssr-dev
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}