apiVersion: v1
kind: Service
metadata:
  labels:
    name: content-api
  name: content-api
  namespace: dev
spec:
  selector:
    name: content-api
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
